theme: jekyll-theme-minimal
show_downloads: ["true"]
logo: /assets/imgs/ITDroid.png
title: ITDroid
tsdllogo: /assets/imgs/horizontalLightBrackgrounds.png

navigation:
  - title: Video
    link: /video.hmtl
